"""empty message

Revision ID: 9a117141b685
Revises: 
Create Date: 2019-12-01 19:56:28.966353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a117141b685'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'address_id')
    # ### end Alembic commands ###
